// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TailorAPI.Migrations
{
    [DbContext(typeof(TailorDbContext))]
    [Migration("20250708114150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ShopId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("int");

                    b.Property<int>("MaxOrders")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StripeProductId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("TailorAPI.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.HasIndex("PlanId");

                    b.HasIndex("ShopId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("TailorAPI.Models.FabricStock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StockID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("FabricTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StockAddDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("StockIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockUse")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockID");

                    b.HasIndex("BranchId");

                    b.HasIndex("FabricTypeID");

                    b.HasIndex("ShopId");

                    b.ToTable("FabricStocks");
                });

            modelBuilder.Entity("TailorAPI.Models.FabricType", b =>
                {
                    b.Property<int>("FabricTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FabricTypeID"));

                    b.Property<decimal>("AvailableStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("FabricName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PricePerMeter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("FabricTypeID");

                    b.HasIndex("BranchId");

                    b.HasIndex("ShopId");

                    b.ToTable("FabricTypes");
                });

            modelBuilder.Entity("TailorAPI.Models.Measurement", b =>
                {
                    b.Property<int>("MeasurementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MeasurementID"));

                    b.Property<float>("Ankle")
                        .HasColumnType("float");

                    b.Property<double>("Arms")
                        .HasColumnType("real");

                    b.Property<float>("Bicep")
                        .HasColumnType("float");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<float>("Calf")
                        .HasColumnType("float");

                    b.Property<double>("Chest")
                        .HasColumnType("real");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("Forearm")
                        .HasColumnType("float");

                    b.Property<double>("Hip")
                        .HasColumnType("real");

                    b.Property<double>("Inseam")
                        .HasColumnType("real");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("LowerBodyMeasurement")
                        .HasColumnType("float");

                    b.Property<double>("Neck")
                        .HasColumnType("real");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<double>("Shoulder")
                        .HasColumnType("real");

                    b.Property<double>("Sleeve")
                        .HasColumnType("real");

                    b.Property<double>("SleeveLength")
                        .HasColumnType("real");

                    b.Property<double>("Thigh")
                        .HasColumnType("real");

                    b.Property<double>("TrouserLength")
                        .HasColumnType("real");

                    b.Property<float>("UpperBodyMeasurement")
                        .HasColumnType("float");

                    b.Property<double>("Waist")
                        .HasColumnType("real");

                    b.Property<float>("Wrist")
                        .HasColumnType("float");

                    b.HasKey("MeasurementID");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("TailorAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("FabricLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FabricTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FabricTypeID");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProductID");

                    b.HasIndex("ShopId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TailorAPI.Models.OtpVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OtpExpiry")
                        .HasColumnType("datetime");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("UserID");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("TailorAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MakingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("BranchId");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TailorAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "SuperAdmin",
                            RoleType = 0
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Admin",
                            RoleType = 0
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Manager",
                            RoleType = 0
                        },
                        new
                        {
                            RoleID = 4,
                            RoleName = "Tailor",
                            RoleType = 0
                        });
                });

            modelBuilder.Entity("TailorAPI.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PlanEndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlanStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShopId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlanId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("TailorAPI.Models.TwilioSms", b =>
                {
                    b.Property<int>("TwilioSmsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TwilioSmsID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("SmsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("TwilioSmsID");

                    b.HasIndex("BranchId");

                    b.HasIndex("OrderID");

                    b.HasIndex("ShopId");

                    b.ToTable("TwilioSms");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Available");

                    b.HasKey("UserID");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleID");

                    b.HasIndex("ShopId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("Customers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("TailorAPI.Models.Branch", b =>
                {
                    b.HasOne("Plan", "Plan")
                        .WithMany("Branches")
                        .HasForeignKey("PlanId");

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("Branches")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("TailorAPI.Models.FabricStock", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("FabricStocks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.FabricType", "FabricType")
                        .WithMany()
                        .HasForeignKey("FabricTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("FabricStocks")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("FabricType");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("TailorAPI.Models.FabricType", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("FabricTypes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("FabricTypes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("TailorAPI.Models.Measurement", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("Measurements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer", "Customer")
                        .WithOne("Measurement")
                        .HasForeignKey("TailorAPI.Models.Measurement", "CustomerId");

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("Measurements")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("TailorAPI.Models.Order", b =>
                {
                    b.HasOne("User", "Assigned")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.FabricType", "fabricType")
                        .WithMany("Orders")
                        .HasForeignKey("FabricTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plan", "Plan")
                        .WithMany("Orders")
                        .HasForeignKey("PlanId");

                    b.HasOne("TailorAPI.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("Orders")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assigned");

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Plan");

                    b.Navigation("Product");

                    b.Navigation("Shop");

                    b.Navigation("fabricType");
                });

            modelBuilder.Entity("TailorAPI.Models.OtpVerification", b =>
                {
                    b.HasOne("User", "user")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TailorAPI.Models.Product", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("Products")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("TailorAPI.Models.Shop", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TailorAPI.Models.TwilioSms", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("TwilioSmss")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("TwilioSmss")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Order");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("TailorAPI.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TailorAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorAPI.Models.Shop", "Shop")
                        .WithMany("Users")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Role");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Navigation("Measurement")
                        .IsRequired();
                });

            modelBuilder.Entity("Plan", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TailorAPI.Models.Branch", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("FabricStocks");

                    b.Navigation("FabricTypes");

                    b.Navigation("Measurements");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("TwilioSmss");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TailorAPI.Models.FabricType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TailorAPI.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TailorAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TailorAPI.Models.Shop", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Customers");

                    b.Navigation("FabricStocks");

                    b.Navigation("FabricTypes");

                    b.Navigation("Measurements");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("TwilioSmss");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
